### ISSUE TITLE
Error when a vignette fragment is imported through 'child=' code chuck option

### ISSUE THREAD

**Issue by MalgorzataOles** [Bioconductor/BiocCheck#17]
Hi,

I'm encountering problems during BiocCheck, which are likely caused by the functions not finding vignette files. In the package I have a master vignette which serves as skeleton for including parts placed in "src" subfolder by using `child=` code chunk option. BiocCheck fails during line `parsedCode <- parseFiles(package_dir)`. The linked [toy example](https://oc.embl.de/index.php/s/YcTzWhUtRW32aJM) reproduces the described behavior, see also the output below.

Best regards,
Małgorzata

```
> R CMD BiocCheck toy_0.1.3.tar.gz 
This is BiocCheck version 1.13.1. BiocCheck is a work in progress.
Output and severity of issues may change. Installing package...
* Checking for version number mismatch...
    This is not a software package, skipping vignette checks...
* Checking version number...
* Checking version number validity...
    Package version 0.1.3; pre-release
* Checking R Version dependency...
* Checking biocViews...
* Checking that biocViews are present...
* Checking for non-trivial biocViews...
* Checking that biocViews come from the same category...
* Checking biocViews validity...
* Checking for recommended biocViews...
* Checking build system compatibility...
* Checking for blank lines in DESCRIPTION...
* Checking for whitespace in DESCRIPTION field names...
* Checking that Package field matches directory/tarball name...
* Checking for Version field...
* Checking for valid maintainer...
* Checking unit tests...
    * NOTE: Consider adding unit tests. We strongly encourage them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
Loading required namespace: knitr
Error in readLines(if (is.character(input2)) { :
  cannot open the connection
Calls: <Anonymous> -> BiocCheck -> parseFiles -> parseFile
Execution halted
```

**Comment by sgibb** [comment]
Same problem here. There reason seems to be that `parseFile` copies the vignette into a temporary directory but doesn't copy the included files:
https://github.com/Bioconductor/BiocCheck/blob/fed2f4da4d1c3dac9f6e30cecb2911bc28b75e62/R/util.R#L165-L173

**Comment by llrs** [comment]
Maybe this old issue is a good issue to take care of in the hackathon ? Although usually not a lot of packages use this functionality...

**Comment by mblue9** [comment]
I just ran into this error. As was trying to find a way to share the same code across Bioconductor vignette and README to reduce code duplication and maintenance, and found a [nifty method](https://www.garrickadenbuie.com/blog/dry-vignette-and-readme/) to share the content using `man/fragments`.

It works well for a CRAN package ([tidyseurat](https://github.com/stemangiola/tidybulk/runs/1159952436?check_suite_focus=true)) but it fails with a couple of Bioconductor packages I tried it with [here](https://github.com/stemangiola/tidybulk/runs/1159952436?check_suite_focus=true) and [here](https://github.com/stemangiola/tidySCE/runs/1084773143?check_suite_focus=true), as BiocCheck gives the same error as reported in this issue. Seems also due to `child=` being used. Would be great if there was a way to make it work.

(ping @stemangiola)

**Comment by stemangiola** [comment]
If I can add my two cents, reconciling the RADME and Vignette roles is something that many projects are trying to do, with a long list of discussion and blog posts.

Furthermore re-utilizing code chunks is incredibly useful to build educational resources around GitHub and Bioconductor.

I would strongly up-vote for tackling this problem with some priority.

**Comment by mtmorgan** [comment]
FWIW a straightforward solution is to make the README a symbolic link to a relevant vignette. Another approach is to use a github action to create the README.md from a vignette (modifying https://github.com/r-lib/actions/tree/master/examples#render-readme; implemented (poorly) at https://github.com/Bioconductor/Gen3/blob/master/.github/workflows/render-vignette-as-readme.yaml)

If this comment https://github.com/Bioconductor/BiocCheck/issues/17#issuecomment-334387192 is on the right track then perhaps there is a pull request that could be developed?

**Comment by mblue9** [comment]
Thanks for the suggestions! They are interesting I hadn't thought of trying things like that. 

I guess that the symlink and github actions methods would require the vignette and README to be identical? With the child method it's quite flexible as you can also have some differences between them. In our case we only have small differences at the moment e.g. including the GitHub actions badge in the README but not in the vignette. But maybe some people might want to include just some of the vignette, or parts from different vignettes. So I think it could be good if possible to find a way to allow the child method and as that would solve the OP's issue with wanting to include child docs.

That comment seems to be on the right track, that the extra files aren't getting copied to where the vignette is being built. As, because this child method works with R CMD Check, I had a look to try to see how they get it to work there. I found this SO post https://stackoverflow.com/questions/50078849/package-build-fails-because-vignette-does-not-find-child-rmd-files It seems they had the same issue with including child docs and it was fixed I think through this patch to R mentioned in that SO post https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17416. But I don't know if that would work here?

**Comment by anhtr** [comment]
I got similar issue when using BiocCheck in GitHub Action. It took me a few days to figure out what's wrong. I thought there's a problem with the library call check. It seemed due to the fact that I used `child =` in vignettes and readme. I wish there's a way to skip that check. Right now the parseFiles call will be executed regardless of any argument in BiocCheck, and it's not very clear why one would get the error without digging deep into the inner working of the function.

```
Bioconductor version 3.12 (BiocManager 1.30.10), ?BiocManager::install for help
This is BiocCheck version 1.26.0. BiocCheck is a work in progress.
Output and severity of issues may change. Installing package...
* Checking Package Dependencies...
Warning in system2(cmd, args, stdout = TRUE, stderr = FALSE, env = "R_DEFAULT_PACKAGES=NULL") :
  running command 'R_DEFAULT_PACKAGES=NULL '/usr/local/lib/R/bin/R' -q --vanilla --slave -f /__w/_temp/Library/BiocCheck/script/checkBadDeps.R --args "/tmp/RtmpQa0lvD/filed677dc33c12/lib/HPAanalyze" 2>/dev/null' had status 1
* Checking if other packages can import this one...
* Checking to see if we understand object initialization...
* Checking for deprecated package usage...
* Checking for remote package usage...
* Checking version number...
* Checking for version number mismatch...
* Checking version number validity...
* Checking package size...
    * ERROR: Package Source tarball exceeds Bioconductor size
      requirement.
        Package Size: 10.3922 MB
        Size Requirement: 5.0000 MB
* Checking individual file sizes...
* Checking biocViews...
* Checking that biocViews are present...
* Checking package type based on biocViews...
    Software
* Checking for non-trivial biocViews...
* Checking that biocViews come from the same category...
* Checking biocViews validity...
* Checking for recommended biocViews...
* Checking build system compatibility...
* Checking for blank lines in DESCRIPTION...
* Checking if DESCRIPTION is well formatted...
* Checking for proper Description: field...
    * WARNING: Description field in the DESCRIPTION file is too concise
* Checking for whitespace in DESCRIPTION field names...
* Checking that Package field matches directory/tarball name...
* Checking for Version field...
* Checking for valid maintainer...
* Checking DESCRIPTION/NAMESPACE consistency...
* Checking vignette directory...
    This is a software package
* Checking library calls...
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> -> parseFiles -> parseFile
Execution halted
Error: Process completed with exit code 1.
```

**Comment by LiNk-NY** [comment]
See #121

**Comment by mblue9** [comment]
Thanks @LiNk-NY for the PR! I've just been trying it out and it works well locally for me, have tested with BiocCheck 1.27.9 and 1.27.13.  

One thing though is it fails with GitHub Actions. here https://github.com/stemangiola/tidybulk/runs/2356663732?check_suite_focus=true#step:24:379
```
Warning in file(con, "r") :
  cannot open file '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//RtmpTqLgjW/file212e1707a88a/tidybulk/inst/doc/../man/fragments/intro.Rmd': No such file or directory
Quitting from lines 16-16 (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//RtmpTqLgjW/file212e1707a88a/tidybulk/inst/doc/../man/fragments/intro.Rmd) 
Error: Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... lapply -> FUN -> knit -> <Anonymous> -> readLines -> file
Execution halted
Error: Process completed with exit code 1.
```

The R CMD Check passes fine, it's just the BiocCheck. I think it's because our child is in `man/fragments` (so we can share content with the readme) and not `vignettes`? I know this may be outside your scope as it does work locally but was wondering if you know if there any way to allow the child to be in e.g. man/fragments like  R CMD Check so that it'll work with Github actions and BiocCheck?

**Comment by LiNk-NY** [comment]
It seems to be a separate issue. Please open a new one with a minimally reproducible example. It may not be in the scope of `BiocCheck`.

**Comment by stemangiola** [comment]
@multimeric
