### ISSUE TITLE
make sure vignette would be built by `R CMD build`

### ISSUE THREAD

**Issue by jimhester** [Bioconductor/BiocCheck#4]

**Comment by b-long** [comment]
:+1:

**Comment by dtenenba** [comment]
Actually, it's a bit more complicated than that, so I may rename the issue to capture some of the additional complexity. There are several possible causes for packages which appear to have vignettes but in which vignettes are not built when you run `R CMD build`.

Usually this is due to missing `Suggests` dependencies, missing `VignetteEngine` field in `DESCRIPTION` file, and/or missing/incorrect information in the YAML preamble of the vignette.

For example I just saw a package whose vignette was not building because the  `VignetteEngine` setting in the vignette (**not** the `DESCRIPTION` file) was `rmarkdown::render`; changing it to `knitr::rmarkdown` caused the vignette to build).

I'm not sure the best way to check for this situation since there are several possible causes and there is no one "correct" group of settings that will guarantee the vignette builds. (Like, why was `rmarkown::render` wrong? Will it work in future? Also, how do you identify a 'non-Sweave vignette'? In the case where we have an .Rmd file it's easy, in the case of an Rnw file it's trickier; usually the way to do it would be to look for the `VignetteEngine` field in `DESCRIPTION` but when that is accidentally omitted...) .

Obviously `BiocCheck` could simply run `R CMD build` but that could take too long. 
Actually maybe it could run it and see if it finishes up within 5 seconds (if not, terminate the process).
If it does finish up quickly, then inspect the generated tarball for files in `inst/doc` (need to confirm of course that these files were not already in `inst/doc` in the original package). If those files are missing (but there are vignette source files in `vignettes/`), then there is a problem.

**Comment by dtenenba** [comment]
Looks like there is still an example that fails after this fix. 

https://tracker.bioconductor.org/issue1390
https://tracker.bioconductor.org/file7084/nucleoSim_0.99.4.tar.gz

This does not indicate an error:

```
> pkgdir <- "~/Downloads/nucleoSim"
> vigns <- tools:::pkgVignettes(dir = pkgdir, check = TRUE)
> vigns$msg
character(0)
>
```

The problem in this case is that they have this in DESCRIPTION:

```
VignetteBuilder: rmarkdown
```

And this in the vignette:

```
%\VignetteEngine{knitr::rmarkdown}
```

IOW, referencing two different packages. Too bad that R does not detect this. Possible bug in R? I might report it.  But we should work around it.

**Comment by dtenenba** [comment]
Just for more context--with version 0.99.3 of nucleoSim, the new code worked as expected:

```
* This is a software package, checking vignette directories...
    * REQUIRED: Files named as vignettes but with no recognized
      vignette engine: 'vignettes/nucleoSim.Rmd' (Is a VignetteBuilder
      field missing?)
```

```
> pkgdir <- '~/Downloads/nucleoSim_0.99.3'
> vigns <- tools:::pkgVignettes(dir = pkgdir, check = TRUE)
> vigns$msg
[1] "Files named as vignettes but with no recognized vignette engine:"
[2] "   'vignettes/nucleoSim.Rmd'"
[3] "(Is a VignetteBuilder field missing?)"
```

If you then add in the line

```
 %\VignetteEngine{knitr::rmarkdown}
```

To the vignette yaml preamble, the code stops working even though it's still wrong (wrong in such a way that the vignette is not built on `R CMD build`). 
So it seems like `pkgVignettes()` checks for that `%\VignetteEngine` line but does not check its correctness.

**Comment by jimhester** [comment]
> (Like, why was rmarkown::render wrong? Will it work in future? Also, how do you identify a 'non-Sweave vignette'? In the case where we have an .Rmd file it's easy, in the case of an Rnw file it's trickier; usually the way to do it would be to look for the VignetteEngine field in DESCRIPTION but when that is accidentally omitted...) 

`rmarkdown::render` is wrong because it is not a registered vignette engine. The rmarkdown package does not register any vignette engines itself. 

The only way to know if a given vignette is non-Sweave is to look for the `%\VignetteEngine{}` metadata line. Looking in the `DESCRIPTION` won't work because a given package could use multiple different vignette engines for different vignettes, including some Sweave and Non-Sweave ones.

The [Non-Sweave Vignettes](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Non_002dSweave-vignettes) section of writing R extensions is probably the best place to look for how this works.

One thing you could do is load the `VignetteBuilder` package and check that it in fact does register a vignette. This would detect the erroneous use of `rmarkdown` as a `VignetteBuilder`.
