### ISSUE TITLE
Checking for units tests in non software packages

### ISSUE THREAD

**Issue by MahShaaban** [Bioconductor/BiocCheck#53]
I am getting this note even though the package in question is not a software package

>  Checking unit tests...
    NOTE: Consider adding unit tests. We strongly encourage them. See
     http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

Is `BiocCheck` supposed to check for unit tests in non software packages? Or should it be skipped just like vignette checks.

Thanks

**Comment by lshep** [comment]
We left it in as it is still somewhat encouraged to have unit tests for data or annotation packages.  The checks could be something like making sure the expected data is present or object generation was executed properly, etc.  If it is too time consuming or not needed or no tests are appropriate than it can be skipped for these types of packages which is why it is a NOTE instead of a WARNING/ERROR.
