### ISSUE TITLE
sapply --> vapply, and 1:length become WARNING

### ISSUE THREAD

**Issue by nturaga** [Bioconductor/BiocCheck#63]
Right now these issues are displayed as `NOTE` tags on the build report, and these should be converted as `WARNING` tags.

**Comment by lcolladotor** [comment]
Maybe as part of this issue, or a companion one, could be adding a little help page at https://github.com/Bioconductor/bioconductor.org on how to go from `sapply()` to `vapply()` through a linked issue there.

**Comment by lcolladotor** [comment]
Here's some example `sapply()` calls I have in a package that I would need to update to `vapply()` https://github.com/leekgroup/recount/search?q=sapply&unscoped_q=sapply.

I'm not the most familiar with `vapply()`, so I don't know if there are `sapply()` cases that are hard to transition to `vapply()`. Just thinking about the docs page suggestion, not the actual `BiocCheck` check.

**Comment by mtmorgan** [comment]
Usually the hard-to-apply cases are the ones where you say
```
value <- sapply(X, FUN, ...)
if (is.list(value)) {
    ## it DIDN'T simplify
    ....
} else {
    # it DID simplify
    ...
}
```
Usually `sapply()` doesn't simplify because `FUN` sometimes returns one type of value, sometimes another. Or sometimes the return value is length x, other times length y.

Usually, the solution is to fix `FUN()`, rather than to avoid `vapply()`. If `FUN()` always returns the same type of value, then the subsequent code is much easier to reason about -- all of the complexity is handled by the modular FUN, rather than getting mixed up in the code that is trying to do something after FUN.

One wants to avoid or at least localize 'cyclomatic complexity'.

**Comment by LiNk-NY** [comment]
I'm closing this. Feel free to re-open if you feel strongly about it.

**Comment by nturaga** [comment]
I don't ;)
