### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by llrs** [Bioconductor/BiocCheck#76]
A clarification on the README of how to install the package and how to use it might help if people don't visit Bioconductor site. 

Also the vignette is missing the sessionInfo at the end.

**Comment by nturaga** [comment]
Some thoughts:

A check for a README.md could be included as NOTE, we don't want to impose that people have a detailed README.md, because we already impose on the detailed vignette. 

- Nitesh, Lori

**Comment by lcolladotor** [comment]
Aye, I agree. With BioC, the idea is that people go to the landing page and find all the info there. If you have a README.md it feels to me like you provide that at your own risk. Otherwise you can end up having to reproduce the entire BioC landing page on a README.md (since that page has a ton of very useful info). Plus you might end up confusing users on how to install a package (github vs bioc).

I like having nice READMEs, but mostly with info that's not redundant with the BioC landing page or vignettes.

**Comment by lcolladotor** [comment]
Related to this issue:

By the way, at `biocthis`, particularly https://github.com/lcolladotor/biocthis/blob/master/inst/templates/package-README#L29-L42 the template I made recently does add the information Lluís requested.

I guess that this new `BiocCheck` check could check whether:

* `BiocManager::install()` is mentioned
* A link to `https://bioconductor.org/packages/{pkg-name}` is included

if a `README.md` file is present in the package.
