### ISSUE TITLE
Make it possible to avoid self-installation of BiocCheck script

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/BiocCheck#78]
Related to Issue #52; as a first step, make it possible to avoid the auto-installation that takes place as soon as the **BiocCheck** package is loaded.  For instance, make it possible to disable this via an R option `BiocCheck.installOnLoad` and/or an environment variable `R_BIOCCHECK_INSTALLONLOAD`. 

https://github.com/Bioconductor/BiocCheck/blob/4687a90efd5a30218320af9eb79f778463397d2e/R/zzz.R#L1-L25

The package is useful also without this installation, e.g.
```r
> BiocCheck::BiocCheck(...)
```

Also, if you have disabled write permissions to where BiocCheck tries to install itself, then you get a warning every time the package is loaded, e.g.
```r
> BiocCheck::BiocCheck(...)
Failed to copy the script/BiocCheck or script/BiocCheckGitClone script to
/home/hb/software/R-devel/tags/R-4-0-0/lib/R/bin. If you want to be able to run 'R CMD BiocCheck'
you'll need to copy it yourself to a directory on your PATH, making sure it is executable. See the
BiocCheck vignette for more information.
```

Labels: Hackathon, Beginner/Intermediate

**Comment by lcolladotor** [comment]
This could be related (I don't fully understand the code here):

On GitHub Actions I ran into issues related to where `BiocCheck` was installed when using the Bioconductor docker images with a shared volume (disk) with the host Ubuntu linux machine. So you end up with 3 `.libPaths()`, with `[1]` being the shared volume and `[2]` and `[3]` being exclusive on docker, such that `BiocManager` installed `BiocCheck` at `[1]` but you needed to move it to `[2]` or `[3]` to run `R CMD BiocCheck` which is why I ended up resorting to `BiocCheck::BiocCheck()`.

Edit: here are more details on the code I had for copying the files across the `.libPaths()` to hack myself around and get `R CMD BiocCheck` to work https://github.com/lcolladotor/biocthis/commit/af22be1905d08624322364e890fd3cc15aedc994#diff-40457677611d00ff5fd9c435c356b068 (with I now avoid by using `BiocCheck::BiocCheck()`)

**Comment by lshep** [comment]
We have decided to remove the command line option for running BiocCheck and BiocCheckGitClone.  BiocCheck and BiocCheckGitClone command line will be deprecated in 3.12 and removed in 3.13. This should allow the writing and self-install portions to be removed.  The documentation and recommended running will be from within R.

**Comment by LiNk-NY** [comment]
@lshep Hi Lori, 
Have we removed this in 3.13?

**Comment by lshep** [comment]
@LiNk-NY Not yet.  I haven't had time to go through and remove and accurate test

**Comment by mikelove** [comment]
Just a heads up, I think `usage()` still recommends running from command line:

https://github.com/Bioconductor/BiocCheck/blob/master/R/BiocCheck.R#L63
